### PR TITLE
fix: validate sources value to be string

### PR DESCRIPTION
**Pull request by danielroe**
Currently using a package that injects an object as `theme` in nuxt.config and is broken since https://github.com/nuxt/framework/pull/7131. Obviously that will need to be fixed in the theme, but in a similar case in future it will be unclear what the issue is because it triggers the following error:

```js
Nuxi 3.0.0-rc.10-27706138.b31405f
Nuxt 3.0.0-rc.10-27706138.b31405f with Nitro 0.5.1-27706249.08ac81b

 ERROR  Cannot start nuxt:  source.startsWith is not a function

  at node_modules/.pnpm/c12@0.2.10/node_modules/c12/dist/index.mjs:174:44
  at Array.some (<anonymous>)
  at resolveConfig (node_modules/.pnpm/c12@0.2.10/node_modules/c12/dist/index.mjs:174:20)
  at extendConfig (node_modules/.pnpm/c12@0.2.10/node_modules/c12/dist/index.mjs:151:27)
  at extendConfig (node_modules/.pnpm/c12@0.2.10/node_modules/c12/dist/index.mjs:156:11)
  at async loadConfig (node_modules/.pnpm/c12@0.2.10/node_modules/c12/dist/index.mjs:114:5)
```

This change makes it warn instead:

```
 WARN  Cannot extend config from {"meta":{"name":"Nuxt Elements","description":"Building blocks for your next application.","author":"NuxtLabs"}} in /private/tmp/studio/node_modules/.pnpm/@nuxt-themes+elements-edge@0.0.1-fdfc0b1/node_modules/@nuxt-themes/elements-edge/theme
```

It would also be equally easy to filter it out at L136 but thought you might prefer the warning for now.

### CODE REVIEW

File: src/loader.ts [hunk 1]
```diff
@@ -161,6 +161,12 @@ const NPM_PACKAGE_RE = /^(@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/
 const jiti = createJiti(null, { cache: false, interopDefault: true, requireCache: false, esmResolve: true })
 
 async function resolveConfig (source: string, opts: LoadConfigOptions): Promise<ResolvedConfig> {
+  if (typeof source !== 'string') {
```
Comment (pi0) [inline src/loader.ts:164]: Maybe we move this check to L140 to filter out wrong sources?
